import { useEffect, useState } from 'react';
import axios from '../api/axios';
import { motion } from 'framer-motion';
import { Heart, Globe, Play, User } from 'lucide-react';

const Community = () => {
    const [scripts, setScripts] = useState([]);
    const [loading, setLoading] = useState(true);

    useEffect(() => {
        const fetchCommunity = async () => {
            try {
                const res = await axios.get('/scripts/community');
                setScripts(res.data);
            } catch (error) {
                console.error(error);
            } finally {
                setLoading(false);
            }
        };
        fetchCommunity();
    }, []);

    const handleLike = async (id) => {
        try {
            await axios.put(`/scripts/${id}/like`);
            setScripts(scripts.map(s => s._id === id ? { ...s, likes: s.likes + 1 } : s));
        } catch (error) {
            console.error(error);
        }
    };

    return (
        <div className="min-h-[calc(100vh-64px)] pt-32 p-4 md:p-8 max-w-7xl mx-auto">
            <motion.h1
                initial={{ opacity: 0, y: -20 }}
                animate={{ opacity: 1, y: 0 }}
                className="text-4xl font-bold mb-2 flex items-center gap-3 tracking-tight"
            >
                <div className="relative">
                    <Globe size={40} className="text-accent animate-pulse-glow" />
                    <div className="absolute inset-0 bg-accent/20 blur-xl rounded-full"></div>
                </div>
                <span className="bg-gradient-to-r from-accent to-primary bg-clip-text text-transparent">Community Feed</span>
            </motion.h1>
            <p className="text-gray-400 mb-10 ml-14 max-w-xl">Discover what's trending. Remix the best viral ad concepts generated by the community.</p>

            {loading ? (
                <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
                    {[1, 2, 3, 4, 5].map(i => (
                        <div key={i} className="glass-panel h-64 rounded-2xl animate-pulse break-inside-avoid"></div>
                    ))}
                </div>
            ) : (
                <div className="columns-1 md:columns-2 lg:columns-3 gap-6 space-y-6">
                    {scripts.map((script, index) => (
                        <motion.div
                            key={script._id}
                            initial={{ opacity: 0, y: 20 }}
                            animate={{ opacity: 1, y: 0 }}
                            transition={{ delay: index * 0.05 }}
                            whileHover={{ y: -5 }}
                            className="glass-panel rounded-2xl p-6 border border-white/5 break-inside-avoid shadow-lg hover:shadow-primary/10 group relative transition-all"
                        >
                            <div className="flex justify-between items-start mb-4">
                                <div>
                                    <h3 className="font-bold text-lg text-white group-hover:text-primary transition-colors">{script.productName}</h3>
                                    <span className="text-xs text-gray-400 flex items-center gap-1 mt-1">
                                        <User size={10} />
                                        Posted {new Date(script.createdAt).toLocaleDateString()}
                                    </span>
                                </div>
                                <button
                                    onClick={() => handleLike(script._id)}
                                    className="flex items-center gap-1.5 text-xs font-medium bg-white/5 hover:bg-pink-500/20 text-gray-300 hover:text-pink-400 px-3 py-1.5 rounded-full transition-colors border border-white/5"
                                >
                                    <Heart size={14} className={script.likes > 0 ? "fill-pink-500 text-pink-500" : ""} />
                                    {script.likes || 0}
                                </button>
                            </div>

                            <div className="bg-black/30 p-4 rounded-xl text-xs text-gray-300 font-mono max-h-60 overflow-hidden relative mb-4 border border-white/5">
                                <p className="leading-relaxed">{script.description}</p>
                                <div className="mt-3 pt-3 border-t border-white/5">
                                    <span className="text-primary font-bold">HOOK:</span> {JSON.parse(script.generatedScript).hook}
                                </div>
                                <div className="absolute bottom-0 left-0 w-full h-12 bg-gradient-to-t from-black/90 to-transparent"></div>
                            </div>

                            <div className="flex flex-wrap gap-2">
                                <span className="text-xs px-2 py-1 rounded bg-secondary/10 text-secondary border border-secondary/20">#{script.tone}</span>
                                <span className="text-xs px-2 py-1 rounded bg-accent/10 text-accent border border-accent/20">#{script.targetAudience}</span>
                            </div>
                        </motion.div>
                    ))}
                </div>
            )}
        </div>
    );
};

export default Community;
